# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(max_length=265, verbose_name='Atalho'),
        ),
    ]
