# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(upload_to='package/fotos', verbose_name='Foto'),
        ),
    ]
