# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='travel_type',
            field=models.CharField(choices=[('ida', 'Viagem apenas de ida'), ('idavolta', 'Viagem de ida e volta')], default='ida', max_length=50),
        ),
    ]
