# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 22:05
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180109_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=265, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(verbose_name='Atalho'),
        ),
    ]
