# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_package_travel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Chegada'),
        ),
        migrations.AlterField(
            model_name='package',
            name='travel_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Partida'),
        ),
        migrations.AlterField(
            model_name='package',
            name='travel_type',
            field=models.CharField(choices=[('ida', 'Viagem apenas de ida'), ('idavolta', 'Viagem de ida e volta')], default='ida', max_length=50, verbose_name='Tipo da Viagem'),
        ),
    ]
