# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 13:38
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171226_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descrição')),
                ('travel_date', models.DateField(blank=True, null=True, verbose_name='Data da Partida')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Data da Chegada')),
                ('image', models.ImageField(default='media/images/1.jpg', upload_to='package/images', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerias',
                'ordering': ['title'],
            },
        ),
    ]
