# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 23:44
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180109_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=248, verbose_name='Descrição'),
        ),
    ]
