# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='local',
            field=models.CharField(default='Selecione o destino', max_length=100),
        ),
    ]
