# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180109_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_image', models.CharField(choices=[('title', ('PIPA',)), ('title', ('PIRANGI',)), ('title', ('PONTA NEGRA',))], max_length=100, verbose_name='Álbum')),
                ('image', models.ImageField(upload_to='gallery/images', verbose_name='Imagem')),
                ('album', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='home.Gallery')),
            ],
        ),
    ]
