# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='id_image',
            field=models.CharField(choices=[('album', 'PIPA'), ('album', 'PIRANGI'), ('album', 'PONTA NEGRA')], max_length=100, verbose_name='Álbum'),
        ),
    ]
