# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180110_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='id_image',
        ),
    ]
